/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupervisorSettingsRouteImport } from './routes/_app/supervisor/settings'
import { Route as AppSupervisorReportsRouteImport } from './routes/_app/supervisor/reports'
import { Route as AppSupervisorPricingRulesRouteImport } from './routes/_app/supervisor/pricing-rules'
import { Route as AppSupervisorPricingQueueRouteImport } from './routes/_app/supervisor/pricing-queue'
import { Route as AppSupervisorExpectedReturnsRouteImport } from './routes/_app/supervisor/expected-returns'
import { Route as AppSupervisorDisputesRouteImport } from './routes/_app/supervisor/disputes'
import { Route as AppSupervisorDashboardRouteImport } from './routes/_app/supervisor/dashboard'
import { Route as AppSellerSettingsRouteImport } from './routes/_app/seller/settings'
import { Route as AppSellerLedgerRouteImport } from './routes/_app/seller/ledger'
import { Route as AppSellerDisputesRouteImport } from './routes/_app/seller/disputes'
import { Route as AppSellerDecisionsRouteImport } from './routes/_app/seller/decisions'
import { Route as AppSellerDashboardRouteImport } from './routes/_app/seller/dashboard'
import { Route as AppSellerCatalogRouteImport } from './routes/_app/seller/catalog'
import { Route as AppBuyerProfileRouteImport } from './routes/_app/buyer/profile'
import { Route as AppBuyerOrdersRouteImport } from './routes/_app/buyer/orders'
import { Route as AppBuyerHomeRouteImport } from './routes/_app/buyer/home'
import { Route as AppBuyerCheckoutRouteImport } from './routes/_app/buyer/checkout'
import { Route as AppBuyerBrowseRouteImport } from './routes/_app/buyer/browse'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminOverviewRouteImport } from './routes/_app/admin/overview'
import { Route as AppAdminNotificationsRouteImport } from './routes/_app/admin/notifications'
import { Route as AppAdminFraudRouteImport } from './routes/_app/admin/fraud'
import { Route as AppBuyerProductIdRouteImport } from './routes/_app/buyer/product.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupervisorSettingsRoute = AppSupervisorSettingsRouteImport.update({
  id: '/supervisor/settings',
  path: '/supervisor/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorReportsRoute = AppSupervisorReportsRouteImport.update({
  id: '/supervisor/reports',
  path: '/supervisor/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorPricingRulesRoute =
  AppSupervisorPricingRulesRouteImport.update({
    id: '/supervisor/pricing-rules',
    path: '/supervisor/pricing-rules',
    getParentRoute: () => AppRoute,
  } as any)
const AppSupervisorPricingQueueRoute =
  AppSupervisorPricingQueueRouteImport.update({
    id: '/supervisor/pricing-queue',
    path: '/supervisor/pricing-queue',
    getParentRoute: () => AppRoute,
  } as any)
const AppSupervisorExpectedReturnsRoute =
  AppSupervisorExpectedReturnsRouteImport.update({
    id: '/supervisor/expected-returns',
    path: '/supervisor/expected-returns',
    getParentRoute: () => AppRoute,
  } as any)
const AppSupervisorDisputesRoute = AppSupervisorDisputesRouteImport.update({
  id: '/supervisor/disputes',
  path: '/supervisor/disputes',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorDashboardRoute = AppSupervisorDashboardRouteImport.update({
  id: '/supervisor/dashboard',
  path: '/supervisor/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerSettingsRoute = AppSellerSettingsRouteImport.update({
  id: '/seller/settings',
  path: '/seller/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerLedgerRoute = AppSellerLedgerRouteImport.update({
  id: '/seller/ledger',
  path: '/seller/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerDisputesRoute = AppSellerDisputesRouteImport.update({
  id: '/seller/disputes',
  path: '/seller/disputes',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerDecisionsRoute = AppSellerDecisionsRouteImport.update({
  id: '/seller/decisions',
  path: '/seller/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerDashboardRoute = AppSellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSellerCatalogRoute = AppSellerCatalogRouteImport.update({
  id: '/seller/catalog',
  path: '/seller/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerProfileRoute = AppBuyerProfileRouteImport.update({
  id: '/buyer/profile',
  path: '/buyer/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerOrdersRoute = AppBuyerOrdersRouteImport.update({
  id: '/buyer/orders',
  path: '/buyer/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerHomeRoute = AppBuyerHomeRouteImport.update({
  id: '/buyer/home',
  path: '/buyer/home',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerCheckoutRoute = AppBuyerCheckoutRouteImport.update({
  id: '/buyer/checkout',
  path: '/buyer/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerBrowseRoute = AppBuyerBrowseRouteImport.update({
  id: '/buyer/browse',
  path: '/buyer/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOverviewRoute = AppAdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationsRoute = AppAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFraudRoute = AppAdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyerProductIdRoute = AppBuyerProductIdRouteImport.update({
  id: '/buyer/product/$id',
  path: '/buyer/product/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/fraud': typeof AppAdminFraudRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/buyer/browse': typeof AppBuyerBrowseRoute
  '/buyer/checkout': typeof AppBuyerCheckoutRoute
  '/buyer/home': typeof AppBuyerHomeRoute
  '/buyer/orders': typeof AppBuyerOrdersRoute
  '/buyer/profile': typeof AppBuyerProfileRoute
  '/seller/catalog': typeof AppSellerCatalogRoute
  '/seller/dashboard': typeof AppSellerDashboardRoute
  '/seller/decisions': typeof AppSellerDecisionsRoute
  '/seller/disputes': typeof AppSellerDisputesRoute
  '/seller/ledger': typeof AppSellerLedgerRoute
  '/seller/settings': typeof AppSellerSettingsRoute
  '/supervisor/dashboard': typeof AppSupervisorDashboardRoute
  '/supervisor/disputes': typeof AppSupervisorDisputesRoute
  '/supervisor/expected-returns': typeof AppSupervisorExpectedReturnsRoute
  '/supervisor/pricing-queue': typeof AppSupervisorPricingQueueRoute
  '/supervisor/pricing-rules': typeof AppSupervisorPricingRulesRoute
  '/supervisor/reports': typeof AppSupervisorReportsRoute
  '/supervisor/settings': typeof AppSupervisorSettingsRoute
  '/buyer/product/$id': typeof AppBuyerProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/fraud': typeof AppAdminFraudRoute
  '/admin/notifications': typeof AppAdminNotificationsRoute
  '/admin/overview': typeof AppAdminOverviewRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/buyer/browse': typeof AppBuyerBrowseRoute
  '/buyer/checkout': typeof AppBuyerCheckoutRoute
  '/buyer/home': typeof AppBuyerHomeRoute
  '/buyer/orders': typeof AppBuyerOrdersRoute
  '/buyer/profile': typeof AppBuyerProfileRoute
  '/seller/catalog': typeof AppSellerCatalogRoute
  '/seller/dashboard': typeof AppSellerDashboardRoute
  '/seller/decisions': typeof AppSellerDecisionsRoute
  '/seller/disputes': typeof AppSellerDisputesRoute
  '/seller/ledger': typeof AppSellerLedgerRoute
  '/seller/settings': typeof AppSellerSettingsRoute
  '/supervisor/dashboard': typeof AppSupervisorDashboardRoute
  '/supervisor/disputes': typeof AppSupervisorDisputesRoute
  '/supervisor/expected-returns': typeof AppSupervisorExpectedReturnsRoute
  '/supervisor/pricing-queue': typeof AppSupervisorPricingQueueRoute
  '/supervisor/pricing-rules': typeof AppSupervisorPricingRulesRoute
  '/supervisor/reports': typeof AppSupervisorReportsRoute
  '/supervisor/settings': typeof AppSupervisorSettingsRoute
  '/buyer/product/$id': typeof AppBuyerProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin/fraud': typeof AppAdminFraudRoute
  '/_app/admin/notifications': typeof AppAdminNotificationsRoute
  '/_app/admin/overview': typeof AppAdminOverviewRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/buyer/browse': typeof AppBuyerBrowseRoute
  '/_app/buyer/checkout': typeof AppBuyerCheckoutRoute
  '/_app/buyer/home': typeof AppBuyerHomeRoute
  '/_app/buyer/orders': typeof AppBuyerOrdersRoute
  '/_app/buyer/profile': typeof AppBuyerProfileRoute
  '/_app/seller/catalog': typeof AppSellerCatalogRoute
  '/_app/seller/dashboard': typeof AppSellerDashboardRoute
  '/_app/seller/decisions': typeof AppSellerDecisionsRoute
  '/_app/seller/disputes': typeof AppSellerDisputesRoute
  '/_app/seller/ledger': typeof AppSellerLedgerRoute
  '/_app/seller/settings': typeof AppSellerSettingsRoute
  '/_app/supervisor/dashboard': typeof AppSupervisorDashboardRoute
  '/_app/supervisor/disputes': typeof AppSupervisorDisputesRoute
  '/_app/supervisor/expected-returns': typeof AppSupervisorExpectedReturnsRoute
  '/_app/supervisor/pricing-queue': typeof AppSupervisorPricingQueueRoute
  '/_app/supervisor/pricing-rules': typeof AppSupervisorPricingRulesRoute
  '/_app/supervisor/reports': typeof AppSupervisorReportsRoute
  '/_app/supervisor/settings': typeof AppSupervisorSettingsRoute
  '/_app/buyer/product/$id': typeof AppBuyerProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/buyer/browse'
    | '/buyer/checkout'
    | '/buyer/home'
    | '/buyer/orders'
    | '/buyer/profile'
    | '/seller/catalog'
    | '/seller/dashboard'
    | '/seller/decisions'
    | '/seller/disputes'
    | '/seller/ledger'
    | '/seller/settings'
    | '/supervisor/dashboard'
    | '/supervisor/disputes'
    | '/supervisor/expected-returns'
    | '/supervisor/pricing-queue'
    | '/supervisor/pricing-rules'
    | '/supervisor/reports'
    | '/supervisor/settings'
    | '/buyer/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/overview'
    | '/admin/settings'
    | '/admin/users'
    | '/buyer/browse'
    | '/buyer/checkout'
    | '/buyer/home'
    | '/buyer/orders'
    | '/buyer/profile'
    | '/seller/catalog'
    | '/seller/dashboard'
    | '/seller/decisions'
    | '/seller/disputes'
    | '/seller/ledger'
    | '/seller/settings'
    | '/supervisor/dashboard'
    | '/supervisor/disputes'
    | '/supervisor/expected-returns'
    | '/supervisor/pricing-queue'
    | '/supervisor/pricing-rules'
    | '/supervisor/reports'
    | '/supervisor/settings'
    | '/buyer/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin/fraud'
    | '/_app/admin/notifications'
    | '/_app/admin/overview'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/buyer/browse'
    | '/_app/buyer/checkout'
    | '/_app/buyer/home'
    | '/_app/buyer/orders'
    | '/_app/buyer/profile'
    | '/_app/seller/catalog'
    | '/_app/seller/dashboard'
    | '/_app/seller/decisions'
    | '/_app/seller/disputes'
    | '/_app/seller/ledger'
    | '/_app/seller/settings'
    | '/_app/supervisor/dashboard'
    | '/_app/supervisor/disputes'
    | '/_app/supervisor/expected-returns'
    | '/_app/supervisor/pricing-queue'
    | '/_app/supervisor/pricing-rules'
    | '/_app/supervisor/reports'
    | '/_app/supervisor/settings'
    | '/_app/buyer/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/supervisor/settings': {
      id: '/_app/supervisor/settings'
      path: '/supervisor/settings'
      fullPath: '/supervisor/settings'
      preLoaderRoute: typeof AppSupervisorSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/reports': {
      id: '/_app/supervisor/reports'
      path: '/supervisor/reports'
      fullPath: '/supervisor/reports'
      preLoaderRoute: typeof AppSupervisorReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/pricing-rules': {
      id: '/_app/supervisor/pricing-rules'
      path: '/supervisor/pricing-rules'
      fullPath: '/supervisor/pricing-rules'
      preLoaderRoute: typeof AppSupervisorPricingRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/pricing-queue': {
      id: '/_app/supervisor/pricing-queue'
      path: '/supervisor/pricing-queue'
      fullPath: '/supervisor/pricing-queue'
      preLoaderRoute: typeof AppSupervisorPricingQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/expected-returns': {
      id: '/_app/supervisor/expected-returns'
      path: '/supervisor/expected-returns'
      fullPath: '/supervisor/expected-returns'
      preLoaderRoute: typeof AppSupervisorExpectedReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/disputes': {
      id: '/_app/supervisor/disputes'
      path: '/supervisor/disputes'
      fullPath: '/supervisor/disputes'
      preLoaderRoute: typeof AppSupervisorDisputesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/dashboard': {
      id: '/_app/supervisor/dashboard'
      path: '/supervisor/dashboard'
      fullPath: '/supervisor/dashboard'
      preLoaderRoute: typeof AppSupervisorDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/settings': {
      id: '/_app/seller/settings'
      path: '/seller/settings'
      fullPath: '/seller/settings'
      preLoaderRoute: typeof AppSellerSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/ledger': {
      id: '/_app/seller/ledger'
      path: '/seller/ledger'
      fullPath: '/seller/ledger'
      preLoaderRoute: typeof AppSellerLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/disputes': {
      id: '/_app/seller/disputes'
      path: '/seller/disputes'
      fullPath: '/seller/disputes'
      preLoaderRoute: typeof AppSellerDisputesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/decisions': {
      id: '/_app/seller/decisions'
      path: '/seller/decisions'
      fullPath: '/seller/decisions'
      preLoaderRoute: typeof AppSellerDecisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/dashboard': {
      id: '/_app/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof AppSellerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seller/catalog': {
      id: '/_app/seller/catalog'
      path: '/seller/catalog'
      fullPath: '/seller/catalog'
      preLoaderRoute: typeof AppSellerCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/profile': {
      id: '/_app/buyer/profile'
      path: '/buyer/profile'
      fullPath: '/buyer/profile'
      preLoaderRoute: typeof AppBuyerProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/orders': {
      id: '/_app/buyer/orders'
      path: '/buyer/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof AppBuyerOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/home': {
      id: '/_app/buyer/home'
      path: '/buyer/home'
      fullPath: '/buyer/home'
      preLoaderRoute: typeof AppBuyerHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/checkout': {
      id: '/_app/buyer/checkout'
      path: '/buyer/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof AppBuyerCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/browse': {
      id: '/_app/buyer/browse'
      path: '/buyer/browse'
      fullPath: '/buyer/browse'
      preLoaderRoute: typeof AppBuyerBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/overview': {
      id: '/_app/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AppAdminOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notifications': {
      id: '/_app/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AppAdminNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/fraud': {
      id: '/_app/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AppAdminFraudRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyer/product/$id': {
      id: '/_app/buyer/product/$id'
      path: '/buyer/product/$id'
      fullPath: '/buyer/product/$id'
      preLoaderRoute: typeof AppBuyerProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminFraudRoute: typeof AppAdminFraudRoute
  AppAdminNotificationsRoute: typeof AppAdminNotificationsRoute
  AppAdminOverviewRoute: typeof AppAdminOverviewRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppBuyerBrowseRoute: typeof AppBuyerBrowseRoute
  AppBuyerCheckoutRoute: typeof AppBuyerCheckoutRoute
  AppBuyerHomeRoute: typeof AppBuyerHomeRoute
  AppBuyerOrdersRoute: typeof AppBuyerOrdersRoute
  AppBuyerProfileRoute: typeof AppBuyerProfileRoute
  AppSellerCatalogRoute: typeof AppSellerCatalogRoute
  AppSellerDashboardRoute: typeof AppSellerDashboardRoute
  AppSellerDecisionsRoute: typeof AppSellerDecisionsRoute
  AppSellerDisputesRoute: typeof AppSellerDisputesRoute
  AppSellerLedgerRoute: typeof AppSellerLedgerRoute
  AppSellerSettingsRoute: typeof AppSellerSettingsRoute
  AppSupervisorDashboardRoute: typeof AppSupervisorDashboardRoute
  AppSupervisorDisputesRoute: typeof AppSupervisorDisputesRoute
  AppSupervisorExpectedReturnsRoute: typeof AppSupervisorExpectedReturnsRoute
  AppSupervisorPricingQueueRoute: typeof AppSupervisorPricingQueueRoute
  AppSupervisorPricingRulesRoute: typeof AppSupervisorPricingRulesRoute
  AppSupervisorReportsRoute: typeof AppSupervisorReportsRoute
  AppSupervisorSettingsRoute: typeof AppSupervisorSettingsRoute
  AppBuyerProductIdRoute: typeof AppBuyerProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminFraudRoute: AppAdminFraudRoute,
  AppAdminNotificationsRoute: AppAdminNotificationsRoute,
  AppAdminOverviewRoute: AppAdminOverviewRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppBuyerBrowseRoute: AppBuyerBrowseRoute,
  AppBuyerCheckoutRoute: AppBuyerCheckoutRoute,
  AppBuyerHomeRoute: AppBuyerHomeRoute,
  AppBuyerOrdersRoute: AppBuyerOrdersRoute,
  AppBuyerProfileRoute: AppBuyerProfileRoute,
  AppSellerCatalogRoute: AppSellerCatalogRoute,
  AppSellerDashboardRoute: AppSellerDashboardRoute,
  AppSellerDecisionsRoute: AppSellerDecisionsRoute,
  AppSellerDisputesRoute: AppSellerDisputesRoute,
  AppSellerLedgerRoute: AppSellerLedgerRoute,
  AppSellerSettingsRoute: AppSellerSettingsRoute,
  AppSupervisorDashboardRoute: AppSupervisorDashboardRoute,
  AppSupervisorDisputesRoute: AppSupervisorDisputesRoute,
  AppSupervisorExpectedReturnsRoute: AppSupervisorExpectedReturnsRoute,
  AppSupervisorPricingQueueRoute: AppSupervisorPricingQueueRoute,
  AppSupervisorPricingRulesRoute: AppSupervisorPricingRulesRoute,
  AppSupervisorReportsRoute: AppSupervisorReportsRoute,
  AppSupervisorSettingsRoute: AppSupervisorSettingsRoute,
  AppBuyerProductIdRoute: AppBuyerProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
